src/littlefs/lfs.pyx
test/lfs/test_file_functions.py

Currently users can only open the filesystem using the mode 'r' or
'w'. Since the file system is in binary mode (and not text mode) users
will expect that they can open using 'rb' or 'wb'.
This adds the ability to use 'rb' or 'wb' as the mode. Which act the
same as 'r' or 'w' respectively.

Allow users to open the filesystem with mode as 'wb' or 'rb'

---

src/littlefs/__init__.py

The order of the returned tuple's contents did not match the description in the
docstring.

Fix docstring for LittleFS.walk()

---

README.rst

When we copy and paste the example code from the README, it returns the following error:
```
fh = lfs.file_open(fs, 'first-file.txt', 'w') as fh:
^
SyntaxError: invalid syntax
```
This pull request fix this error.

Fix example from README (SyntaxError)

---

test/test_version.py

Updates littlefs to the latest release, which incurs a disk version update. Tested locally with `pytest test`.

Bump littlefs to 2.6.1

---

.github/workflows/deploy.yml
README.rst

Adds CI for building:
* MacOS ARM64 (M1/M2 macs) copied from my [python-template](https://github.com/BrianPugh/python-template).
* It's a separate job because it has to implement a few workarounds.
* Linux ARM64 (helpful for many SBCs)
* This significantly slows down the build process (maybe ~1hr?), but I think its worth it to make raspberry-pi people lives' easier.
* Update README with available prebuilt wheels

ARM prebuilt binaries

---

.gitignore
src/littlefs/lfs.pyx

I tried installing this with python 3.11.4 on macos running on an M1 chip.
I was getting cython-related errors like:
```
Error compiling Cython file:
------------------------------------------------------------
...
cdef lfs_config _impl
cdef dict __dict__
def __cinit__(self):
self._impl.read = &_lfs_read
^
------------------------------------------------------------
src/littlefs/lfs.pyx:72:26: Cannot assign type 'int (*)(const lfs_config *, lfs_block_t, lfs_off_t, void *, lfs_size_t) except? -1' to 'int (*)(const lfs_config *, lfs_block_t, lfs_off_t, void *, lfs_size_t) noexcept'
```
I believe this is due to the [recent Cython 3.0.0 released on July 17, 2023](https://cython.readthedocs.io/en/latest/src/changes.html#exception-handling)
>Cython-implemented C functions now propagate …

Bugfix noexcept (Cython 3.0.0 compatibility)

---

test/test_version.py

This PR bumps the littlefs to release 2.7, see changelog upstream:
https://github.com/littlefs-project/littlefs/releases/tag/v2.7.0
In short, this release brings in new `lfs_fs_stat` function and ability to choose on-disk version. I will create a separate PR for each of these features.
Tested with `pytest test` only.

Bumped littlefs to version 2.7.

---

src/littlefs/__init__.py
src/littlefs/lfs.pyi
src/littlefs/lfs.pyx

low priority PR, just solidifies the LFSConfig constructor signature. No functional change.

LFSConfig now uses proper keyword arguments

---

setup.py
src/littlefs/__init__.py
src/littlefs/__main__.py
src/littlefs/lfs.pyi
src/littlefs/lfs.pyx

This PR does a few things:
- Unrelated to anything else, I added `littlefs-python --version` to the cli.
- I increased `LFS_NAME_MAX` macro definition from the default `255` to `32767`.
- Pros:
- LittleFS supports any `name_max` configuration that is smaller than the version the driver was compiled with.
- This effectively means that littlefs-python can support any reasonable use-case.
- 32767 was chosen because it's the Windows maximum path length; I doubt any reasonable use-case would even approach this value.
- Cons:
- The `lfs_info` struct is now `32512` larger in `littlefs-python`. I don't think any reasonable user would care about this.
- The `lfs_migrate` in `littlefs-python` also now uses `32512` more memory. This is a rarely used function, and also no reasonable user would care …

Expose name max length to CLI

---

src/littlefs/__init__.py
test/test_remove_rename.py

Allows for recursively deleting a directory.
Technically, by changing the return value from `int` to `None`, this is a backwards incompatible change, but the previous return value could only ever be `0` as negative values are promoted to exceptions. I don't imagine this would impact any reasonable use-case.

add recursive=False flag to remove method

---

README.rst
docs/examples/index.rst
docs/usage.rst
pyproject.toml
src/littlefs/__init__.py
src/littlefs/lfs.pxd
src/littlefs/lfs.pyx
test/lfs/conftest.py
test/lfs/test_fs_functions.py
test/test_attr.py
test/test_remove_rename.py

I added a terse configuration for [Codespell](https://github.com/codespell-project/codespell) to the pyproject.toml, and fixed the identified typos.
I also fixed an incorrect documentation reference where `os.walk` was intended.

Fix typos/references (via Codespell)

---

setup.py
src/littlefs/lfs.pyx
test/test_name_max.py

Addresses https://github.com/jrast/littlefs-python/issues/61

reduce LFS_NAME_MAX to 1022, the maximum valid value LittleFS supports.

---

README.rst
setup.py

CI is already building 3.12 wheels. So this is just metadata/readme updates.

update python 3.12 identifier and readme. 

---

.gitignore
README.rst
src/littlefs/__init__.py

Allows for better autocompletion in IDEs. Also substantially reduces namespace pollution for people that (poorly) use `from littlefs import *`.

Specify __all__ in __init__.py

---

src/littlefs/lfs.pxd
src/littlefs/lfs.pyi
src/littlefs/lfs.pyx
test/lfs/test_fs_functions.py

- Added TYPE_REG and TYPE_DIR as constants to the LFSStat class.

Use NamedTuple instead of namedtuple in lfs.pyx.

---

src/littlefs/__init__.py

Hello.
I know Python 3.7 isn't officially supported, but it seems to work with this small change. It would be great if this change gets accepted because then it would make it easier to integrate with esp-idf versions v5.0 and v5.1, because their minimal Python version is indeed 3.7 (only the latest esp-idf v5.2 bumps this to 3.8).
The current f-string = self-documenting expression breaks our internal CI when trying to backport official littlefs example from v5.2 to v5.1 and v5.0 because they use the older Python version.
Thank you!

Remove the f-string self-documenting expression for better Python 3.7 support

---

src/littlefs/lfs.pyi

It seems all versions of mypy between 1.0.1 and 1.9.0 crash due to this definition ( https://github.com/python/mypy/issues/17059 ).
This seems to be a workaround. However, I'm not sure if the `lfs.pyi` is auto-generated or hand-written. There may be a better solution to this.

Avoid undefined LFS_TYPE_REG/DIR.

---

README.rst
src/littlefs/__init__.py
src/littlefs/__main__.py

@jrast In this PR I reworked the CLI a bit to (IMHO) be a bit more intuitive to use. There is no longer as many unified keyword options, but each command now has positional arguments in the order you would expect them. Also, more information (such as block-count) is now inferred from the context.
Since this is all breaking changes, I would also be tempted to rename `create` to `pack` to use the same language as the `unpack` command.

Rework CLI

---

.github/workflows/deploy.yml
.github/workflows/run-tests.yml
README.rst

I've had a little bit of a change of heart; may as well support python 3.7 as long as esp-idf does. No need to make people using espressif chips lives more difficult.

have ci build cp37 wheels

---

src/littlefs/__main__.py

When listing contents of a littlefs-binary, `littlefs-python` throws an error, when the block-size argument is not passed.
```
$ littlefs-python list fs.bin                                                                                    Mi 12 Feb 2025 06:38:19 CET
Traceback (most recent call last):
File "/nix/store/71b4kzb409hl1p1a0p6kca0czd1nc4ds-python3.12-littlefs-python-0.13.1/bin/.littlefs-python-wrapped", line 9, in <module>
sys.exit(main())
^^^^^^
File "/nix/store/71b4kzb409hl1p1a0p6kca0czd1nc4ds-python3.12-littlefs-python-0.13.1/lib/python3.12/site-packages/littlefs/__main__.py", line 308, in main
return args.func(parser, args)
^^^^^^^^^^^^^^^^^^^^^^^
File "/nix/store/71b4kzb409hl1p1a0p6kca0czd1nc4ds-python3.12-littlefs-python-0.13.1/lib/python3.12/site-packages/littlefs/__main_ …
```

block-size should be required on list command
